export default {
  SHOW_EXPRESS_PANEL: 'SHOW_EXPRESS_PANEL',
  HIDE_EXPRESS_PANEL: 'HIDE_EXPRESS_PANEL',
  FETCH_AUTHOR_POPULAR_QUESTIONS: 'FETCH_AUTHOR_POPULAR_QUESTIONS',
  FETCH_TAG_POPULAR_QUESTIONS: 'FETCH_TAG_POPULAR_QUESTIONS',
  SHOW_AUTHOR_POPULAR_QUESTIONS: 'SHOW_AUTHOR_POPULAR_QUESTIONS',
  SHOW_TAG_POPULAR_QUESTIONS: 'SHOW_TAG_POPULAR_QUESTIONS',
  SET_EXPRESS_PANEL_PAGE_NUMBER: 'SET_EXPRESS_PANEL_PAGE_NUMBER',
  SET_EXPRESS_PANEL_PAGE_SIZE: 'SET_EXPRESS_PANEL_PAGE_SIZE',
  SET_EXPRESS_PANEL_ENTITY_ID: 'SET_EXPRESS_PANEL_ENTITY_ID',
};
